import type { SeedFood } from './types.js';

/**
 * База продуктов, ~300 позиций русской домашней кухни.
 *
 * КБЖУ — на 100 г ГОТОВОГО продукта. Варёная гречка, а не сухая крупа;
 * жареная котлета, а не фарш. Это частый источник ошибок в трекерах:
 * человек взвешивает то, что лежит в тарелке, а таблица даёт сухой вес.
 *
 * `carb` — общие углеводы, клетчатка входит в них; `fiber` показывает, сколько
 * из них клетчатки. Конвенция USDA, а не маркировки по ТР ТС, где «углеводы»
 * означают усвояемые. Смешивать эти два счёта в одной таблице нельзя.
 *
 * `portion` — типичная порция в граммах, чтобы добавлять приём в один тап.
 * `isSweet` — попадает в отдельный подбюджет сладкого (FR-3.x).
 *
 * Файл читается глазами и правится руками. Значения округлены до вида,
 * в котором их печатают на упаковках, точность до десятых долей грамма
 * здесь избыточна.
 */
export const foods: SeedFood[] = [
  // ─────────────────────────────────────────── мясо и птица
  { id: 'chicken-breast-boiled', name: 'Куриная грудка отварная', kcal: 137, protein: 29.8, fat: 1.8, carb: 0.5, portion: 150 },
  { id: 'chicken-breast-baked', name: 'Куриная грудка запечённая', kcal: 165, protein: 31, fat: 3.6, carb: 0, portion: 150 },
  { id: 'chicken-breast-grilled', name: 'Куриная грудка на гриле', kcal: 150, protein: 30, fat: 3.2, carb: 0, portion: 150 },
  { id: 'chicken-breast-fried', name: 'Куриное филе жареное', kcal: 197, protein: 28, fat: 8.5, carb: 1, portion: 150 },
  { id: 'chicken-thigh-skinless', name: 'Куриное бедро без кожи запечённое', kcal: 185, protein: 25, fat: 9, carb: 0, portion: 120 },
  { id: 'chicken-thigh-skin', name: 'Куриное бедро с кожей запечённое', kcal: 232, protein: 23, fat: 15, carb: 0, portion: 120 },
  { id: 'chicken-drumstick-boiled', name: 'Куриная голень отварная', kcal: 158, protein: 24, fat: 6.5, carb: 0, portion: 100 },
  { id: 'chicken-liver-stewed', name: 'Куриная печень тушёная', kcal: 165, protein: 21, fat: 8, carb: 2, portion: 120 },
  { id: 'chicken-hearts-stewed', name: 'Куриные сердечки тушёные', kcal: 180, protein: 17, fat: 12, carb: 1, portion: 100 },
  { id: 'turkey-fillet-boiled', name: 'Индейка филе отварное', kcal: 130, protein: 29, fat: 1.5, carb: 0, portion: 150 },
  { id: 'turkey-thigh-baked', name: 'Индейка бедро запечённое', kcal: 175, protein: 24, fat: 8.5, carb: 0, portion: 130 },
  { id: 'beef-boiled', name: 'Говядина отварная', kcal: 220, protein: 26, fat: 12, carb: 0, portion: 120 },
  { id: 'beef-stewed', name: 'Говядина тушёная', kcal: 232, protein: 25, fat: 14, carb: 1.5, portion: 150 },
  { id: 'beef-mince-fried', name: 'Говяжий фарш жареный', kcal: 250, protein: 24, fat: 17, carb: 0, portion: 120 },
  { id: 'beef-steak', name: 'Стейк говяжий жареный', kcal: 280, protein: 25, fat: 20, carb: 0, portion: 200 },
  { id: 'veal-boiled', name: 'Телятина отварная', kcal: 130, protein: 27, fat: 2, carb: 0, portion: 120 },
  { id: 'beef-liver-stewed', name: 'Печень говяжья тушёная', kcal: 165, protein: 18, fat: 9, carb: 4, portion: 120 },
  { id: 'pork-baked', name: 'Свинина запечённая', kcal: 270, protein: 23, fat: 20, carb: 0, portion: 120 },
  { id: 'pork-chop-fried', name: 'Свиная отбивная жареная', kcal: 300, protein: 22, fat: 23, carb: 2, portion: 120 },
  { id: 'pork-shashlik', name: 'Шашлык свиной', kcal: 290, protein: 22, fat: 22, carb: 1, portion: 200 },
  { id: 'lamb-stewed', name: 'Баранина тушёная', kcal: 270, protein: 22, fat: 20, carb: 0, portion: 120 },
  { id: 'rabbit-stewed', name: 'Кролик тушёный', kcal: 175, protein: 25, fat: 8, carb: 0, portion: 130 },
  { id: 'duck-breast-baked', name: 'Утиная грудка запечённая', kcal: 250, protein: 23, fat: 17, carb: 0, portion: 130 },
  { id: 'beef-stroganoff', name: 'Бефстроганов', kcal: 200, protein: 17, fat: 13, carb: 4, portion: 180 },
  { id: 'cutlet-chicken-steamed', name: 'Котлета куриная паровая', kcal: 155, protein: 17, fat: 8, carb: 5, portion: 100 },
  { id: 'cutlet-beef-fried', name: 'Котлета говяжья жареная', kcal: 250, protein: 16, fat: 18, carb: 8, portion: 100 },
  { id: 'meatballs-rice', name: 'Тефтели с рисом', kcal: 190, protein: 13, fat: 11, carb: 9, portion: 150 },
  { id: 'plov-beef', name: 'Плов с говядиной', kcal: 190, protein: 9, fat: 8, carb: 21, portion: 250 },
  { id: 'kholodets', name: 'Холодец мясной', kcal: 120, protein: 12, fat: 8, carb: 0.5, portion: 150 },
  { id: 'buzhenina', name: 'Буженина', kcal: 240, protein: 16, fat: 19, carb: 1, portion: 80 },

  // ─────────────────────────────────────────── колбасы и мясные полуфабрикаты
  { id: 'ham-chicken', name: 'Ветчина куриная', kcal: 125, protein: 16, fat: 6, carb: 1.5, portion: 50 },
  { id: 'ham-pork', name: 'Ветчина свиная', kcal: 230, protein: 14, fat: 19, carb: 1, portion: 50 },
  { id: 'sausage-doktorskaya', name: 'Колбаса варёная «Докторская»', kcal: 250, protein: 13, fat: 22, carb: 1.5, portion: 50 },
  { id: 'sausage-smoked', name: 'Колбаса сырокопчёная', kcal: 460, protein: 20, fat: 42, carb: 1, portion: 30 },
  { id: 'sosiski', name: 'Сосиски молочные', kcal: 265, protein: 11, fat: 24, carb: 2, portion: 100 },
  { id: 'sardelki', name: 'Сардельки', kcal: 230, protein: 11, fat: 20, carb: 2, portion: 100 },
  { id: 'bacon-fried', name: 'Бекон жареный', kcal: 500, protein: 23, fat: 45, carb: 1, portion: 30 },
  { id: 'karbonad-smoked', name: 'Карбонад копчёный', kcal: 180, protein: 16, fat: 13, carb: 0, portion: 50 },
  { id: 'grudinka-smoked', name: 'Грудинка копчёная', kcal: 480, protein: 10, fat: 50, carb: 0, portion: 30 },
  { id: 'pelmeni-boiled', name: 'Пельмени варёные', kcal: 220, protein: 11, fat: 10, carb: 22, portion: 250 },

  // ─────────────────────────────────────────── рыба и морепродукты
  { id: 'cod-boiled', name: 'Треска отварная', kcal: 78, protein: 17.8, fat: 0.7, carb: 0, portion: 150 },
  { id: 'cod-baked', name: 'Треска запечённая', kcal: 90, protein: 20, fat: 1, carb: 0, portion: 150 },
  { id: 'cod-battered', name: 'Треска в кляре жареная', kcal: 210, protein: 16, fat: 11, carb: 12, portion: 150 },
  { id: 'pollock-boiled', name: 'Минтай отварной', kcal: 79, protein: 17.6, fat: 1, carb: 0, portion: 150 },
  { id: 'hake-boiled', name: 'Хек отварной', kcal: 95, protein: 18.5, fat: 2.3, carb: 0, portion: 150 },
  { id: 'zander-boiled', name: 'Судак отварной', kcal: 97, protein: 21, fat: 1.3, carb: 0, portion: 150 },
  { id: 'tilapia-baked', name: 'Тилапия запечённая', kcal: 110, protein: 22, fat: 2.5, carb: 0, portion: 150 },
  { id: 'halibut-baked', name: 'Палтус запечённый', kcal: 190, protein: 19, fat: 12, carb: 0, portion: 130 },
  { id: 'pink-salmon-boiled', name: 'Горбуша отварная', kcal: 168, protein: 22.9, fat: 7.8, carb: 0, portion: 130 },
  { id: 'pink-salmon-baked', name: 'Горбуша запечённая', kcal: 175, protein: 23, fat: 9, carb: 0, portion: 130 },
  { id: 'salmon-baked', name: 'Лосось запечённый', kcal: 200, protein: 22, fat: 12, carb: 0, portion: 130 },
  { id: 'salmon-salted', name: 'Сёмга слабосолёная', kcal: 200, protein: 21, fat: 13, carb: 0, portion: 60 },
  { id: 'trout-baked', name: 'Форель запечённая', kcal: 190, protein: 21, fat: 11, carb: 0, portion: 130 },
  { id: 'mackerel-baked', name: 'Скумбрия запечённая', kcal: 240, protein: 19, fat: 18, carb: 0, portion: 100 },
  { id: 'mackerel-smoked', name: 'Скумбрия копчёная', kcal: 220, protein: 21, fat: 15, carb: 0, portion: 80 },
  { id: 'herring-salted', name: 'Сельдь солёная', kcal: 250, protein: 17, fat: 20, carb: 0, portion: 70 },
  { id: 'tuna-canned', name: 'Тунец консервированный в собственном соку', kcal: 96, protein: 21, fat: 1, carb: 0, portion: 100 },
  { id: 'sardine-canned', name: 'Сардина в масле консервированная', kcal: 220, protein: 17, fat: 17, carb: 0, portion: 80 },
  { id: 'shproty', name: 'Шпроты', kcal: 360, protein: 17, fat: 32, carb: 0, portion: 50 },
  { id: 'pollock-roe', name: 'Икра минтая', kcal: 130, protein: 28, fat: 2, carb: 0, portion: 40 },
  { id: 'shrimp-boiled', name: 'Креветки отварные', kcal: 95, protein: 20, fat: 1.5, carb: 0, portion: 100 },
  { id: 'squid-boiled', name: 'Кальмар отварной', kcal: 110, protein: 18, fat: 2.2, carb: 2, portion: 100 },
  { id: 'mussels-boiled', name: 'Мидии отварные', kcal: 95, protein: 17, fat: 2, carb: 3, portion: 100 },
  { id: 'crab-sticks', name: 'Крабовые палочки', kcal: 95, protein: 6, fat: 1, carb: 14, portion: 60 },
  { id: 'fish-cutlet', name: 'Рыбная котлета', kcal: 160, protein: 14, fat: 8, carb: 8, portion: 100 },

  // ─────────────────────────────────────────── яйца
  { id: 'egg-boiled', name: 'Яйцо куриное варёное', kcal: 157, protein: 12.7, fat: 10.9, carb: 0.7, portion: 55, units: [{ name: '1 шт', grams: 55 }] },
  { id: 'egg-fried', name: 'Яйцо куриное жареное', kcal: 200, protein: 13, fat: 16, carb: 1, portion: 60, units: [{ name: '1 шт', grams: 60 }] },
  { id: 'egg-white-boiled', name: 'Яичный белок варёный', kcal: 48, protein: 11, fat: 0.2, carb: 0.7, portion: 33, units: [{ name: '1 шт', grams: 33 }] },
  { id: 'egg-yolk-boiled', name: 'Яичный желток варёный', kcal: 350, protein: 16, fat: 31, carb: 1, portion: 20, units: [{ name: '1 шт', grams: 20 }] },
  { id: 'omelette-milk', name: 'Омлет с молоком', kcal: 185, protein: 12, fat: 14, carb: 2, portion: 150 },

  // ─────────────────────────────────────────── молочное
  { id: 'milk-1-5', name: 'Молоко 1.5%', kcal: 44, protein: 2.9, fat: 1.5, carb: 4.7, portion: 250, units: [{ name: '1 стакан', grams: 250 }] },
  { id: 'milk-2-5', name: 'Молоко 2.5%', kcal: 52, protein: 2.9, fat: 2.5, carb: 4.7, portion: 250, units: [{ name: '1 стакан', grams: 250 }] },
  { id: 'milk-3-2', name: 'Молоко 3.2%', kcal: 60, protein: 2.9, fat: 3.2, carb: 4.7, portion: 250, units: [{ name: '1 стакан', grams: 250 }] },
  { id: 'kefir-1', name: 'Кефир 1%', kcal: 40, protein: 3, fat: 1, carb: 4, portion: 250, units: [{ name: '1 стакан', grams: 250 }] },
  { id: 'kefir-2-5', name: 'Кефир 2.5%', kcal: 53, protein: 2.9, fat: 2.5, carb: 4, portion: 250, units: [{ name: '1 стакан', grams: 250 }] },
  { id: 'ryazhenka', name: 'Ряженка 4%', kcal: 67, protein: 2.9, fat: 4, carb: 4.2, portion: 250 },
  { id: 'yogurt-natural', name: 'Йогурт натуральный 3.2%', kcal: 66, protein: 5, fat: 3.2, carb: 4, portion: 150 },
  { id: 'yogurt-greek', name: 'Йогурт греческий 2%', kcal: 73, protein: 9, fat: 2, carb: 4, portion: 150 },
  { id: 'yogurt-drinking', name: 'Йогурт питьевой с фруктами', kcal: 75, protein: 2.8, fat: 1.5, carb: 12.5, portion: 250 },
  { id: 'cottage-cheese-0', name: 'Творог 0%', kcal: 71, protein: 16.5, fat: 0.1, carb: 1.3, portion: 200 },
  { id: 'cottage-cheese-5', name: 'Творог 5%', kcal: 121, protein: 17, fat: 5, carb: 1.8, portion: 200 },
  { id: 'cottage-cheese-9', name: 'Творог 9%', kcal: 159, protein: 16.7, fat: 9, carb: 2, portion: 200 },
  { id: 'cottage-cheese-18', name: 'Творог 18%', kcal: 232, protein: 15, fat: 18, carb: 2.8, portion: 150 },
  { id: 'curd-mass-raisins', name: 'Творожная масса с изюмом', kcal: 340, protein: 7, fat: 23, carb: 28, portion: 100, isSweet: true },
  { id: 'glazed-curd-bar', name: 'Сырок глазированный', kcal: 400, protein: 8, fat: 25, carb: 35, portion: 45, isSweet: true, units: [{ name: '1 шт', grams: 45 }] },
  { id: 'sour-cream-15', name: 'Сметана 15%', kcal: 160, protein: 2.6, fat: 15, carb: 3, portion: 30 },
  { id: 'sour-cream-20', name: 'Сметана 20%', kcal: 206, protein: 2.8, fat: 20, carb: 3.2, portion: 30 },
  { id: 'cream-10', name: 'Сливки 10%', kcal: 118, protein: 3, fat: 10, carb: 4, portion: 50 },
  { id: 'cream-33', name: 'Сливки 33%', kcal: 322, protein: 2.2, fat: 33, carb: 3.5, portion: 30 },
  { id: 'cheese-russian', name: 'Сыр Российский', kcal: 364, protein: 23, fat: 29, carb: 0.3, portion: 30 },
  { id: 'cheese-gouda', name: 'Сыр Гауда', kcal: 356, protein: 25, fat: 27, carb: 2, portion: 30 },
  { id: 'cheese-mozzarella', name: 'Сыр Моцарелла', kcal: 280, protein: 22, fat: 21, carb: 2, portion: 40 },
  { id: 'cheese-adygei', name: 'Сыр Адыгейский', kcal: 240, protein: 19, fat: 18, carb: 1.5, portion: 50 },
  { id: 'cheese-processed', name: 'Сыр плавленый', kcal: 290, protein: 12, fat: 25, carb: 3, portion: 30 },
  { id: 'cheese-cream', name: 'Сыр творожный', kcal: 250, protein: 6, fat: 24, carb: 3, portion: 30 },
  { id: 'brynza', name: 'Брынза', kcal: 260, protein: 17, fat: 20, carb: 0.4, portion: 40 },
  { id: 'butter', name: 'Масло сливочное 82.5%', kcal: 748, protein: 0.5, fat: 82.5, carb: 0.8, portion: 10 },
  { id: 'ice-cream-plombir', name: 'Мороженое пломбир', kcal: 230, protein: 3.5, fat: 15, carb: 21, portion: 100, isSweet: true },
  { id: 'ice-cream-eskimo', name: 'Мороженое эскимо', kcal: 270, protein: 3.5, fat: 20, carb: 20, portion: 80, isSweet: true },
  { id: 'condensed-milk', name: 'Сгущённое молоко', kcal: 320, protein: 7, fat: 8.5, carb: 56, portion: 30, isSweet: true },
  { id: 'condensed-milk-boiled', name: 'Сгущённое молоко варёное', kcal: 330, protein: 7, fat: 9, carb: 56, portion: 30, isSweet: true },

  // ─────────────────────────────────────────── крупы, гарниры, макароны
  { id: 'buckwheat-boiled', name: 'Гречка варёная', kcal: 92, protein: 3.4, fat: 0.6, carb: 17.1, portion: 200 },
  { id: 'buckwheat-mushrooms', name: 'Гречка с грибами', kcal: 110, protein: 4, fat: 3, carb: 17, portion: 200 },
  { id: 'rice-white-boiled', name: 'Рис белый варёный', kcal: 116, protein: 2.4, fat: 0.2, carb: 25, portion: 180 },
  { id: 'rice-brown-boiled', name: 'Рис бурый варёный', kcal: 110, protein: 2.6, fat: 0.9, carb: 22, portion: 180 },
  { id: 'oatmeal-water', name: 'Овсяная каша на воде', kcal: 88, protein: 3, fat: 1.7, carb: 15, portion: 250 },
  { id: 'oatmeal-milk', name: 'Овсяная каша на молоке', kcal: 105, protein: 3.2, fat: 2.4, carb: 17, portion: 250 },
  { id: 'pearl-barley-boiled', name: 'Перловка варёная', kcal: 106, protein: 2.9, fat: 0.4, carb: 23, portion: 180 },
  { id: 'millet-porridge', name: 'Пшённая каша на воде', kcal: 90, protein: 3, fat: 0.7, carb: 17, portion: 200 },
  { id: 'barley-porridge', name: 'Ячневая каша', kcal: 96, protein: 2.6, fat: 0.4, carb: 20, portion: 200 },
  { id: 'corn-porridge', name: 'Кукурузная каша', kcal: 90, protein: 2.5, fat: 1.2, carb: 17.5, portion: 200 },
  { id: 'semolina-milk', name: 'Манная каша на молоке', kcal: 100, protein: 3, fat: 3, carb: 15, portion: 250 },
  { id: 'bulgur-boiled', name: 'Булгур варёный', kcal: 83, protein: 3, fat: 0.2, carb: 18.6, portion: 180 },
  { id: 'quinoa-boiled', name: 'Киноа варёная', kcal: 120, protein: 4.4, fat: 1.9, carb: 21, portion: 180 },
  { id: 'couscous-boiled', name: 'Кускус варёный', kcal: 112, protein: 3.8, fat: 0.2, carb: 23, portion: 180 },
  { id: 'pasta-boiled', name: 'Макароны отварные', kcal: 135, protein: 4.5, fat: 0.6, carb: 27, portion: 200 },
  { id: 'pasta-durum-boiled', name: 'Макароны из твёрдых сортов отварные', kcal: 140, protein: 5, fat: 0.7, carb: 28, portion: 200 },
  { id: 'soba-boiled', name: 'Гречневая лапша соба варёная', kcal: 130, protein: 5.5, fat: 0.1, carb: 24, portion: 180 },
  { id: 'rice-noodles-boiled', name: 'Рисовая лапша варёная', kcal: 110, protein: 1.8, fat: 0.2, carb: 25, portion: 180 },
  { id: 'potato-boiled', name: 'Картофель отварной', kcal: 82, protein: 2, fat: 0.4, carb: 17, portion: 200 },
  { id: 'potato-mashed', name: 'Картофельное пюре на молоке', kcal: 106, protein: 2.2, fat: 3.3, carb: 16, portion: 200 },
  { id: 'potato-baked', name: 'Картофель запечённый', kcal: 95, protein: 2.3, fat: 0.3, carb: 20, portion: 200 },
  { id: 'potato-fried', name: 'Картофель жареный', kcal: 190, protein: 2.8, fat: 9.5, carb: 23, portion: 200 },
  { id: 'potato-fries', name: 'Картофель фри', kcal: 310, protein: 3.4, fat: 15, carb: 40, portion: 150 },
  { id: 'plov-vegetable', name: 'Плов овощной', kcal: 150, protein: 3, fat: 5, carb: 24, portion: 250 },
  { id: 'muesli-dried-fruit', name: 'Мюсли с сухофруктами', kcal: 350, protein: 9, fat: 5, carb: 65, portion: 50 },
  { id: 'granola', name: 'Гранола', kcal: 430, protein: 10, fat: 17, carb: 60, portion: 50, isSweet: true },
  { id: 'corn-flakes', name: 'Хлопья кукурузные', kcal: 360, protein: 7, fat: 1, carb: 84, portion: 40, isSweet: true },
  { id: 'oat-bran', name: 'Отруби овсяные', kcal: 320, protein: 17, fat: 7, carb: 50, fiber: 15, portion: 20 },

  // ─────────────────────────────────────────── бобовые
  { id: 'lentils-boiled', name: 'Чечевица варёная', kcal: 111, protein: 9, fat: 0.4, carb: 20, fiber: 8, portion: 180 },
  { id: 'beans-red-boiled', name: 'Фасоль красная варёная', kcal: 123, protein: 8.7, fat: 0.5, carb: 21, fiber: 6, portion: 150 },
  { id: 'beans-white-boiled', name: 'Фасоль белая варёная', kcal: 120, protein: 8, fat: 0.5, carb: 21, fiber: 6, portion: 150 },
  { id: 'chickpeas-boiled', name: 'Нут варёный', kcal: 164, protein: 8.9, fat: 2.6, carb: 27, fiber: 8, portion: 150 },
  { id: 'peas-boiled', name: 'Горох варёный', kcal: 118, protein: 8, fat: 0.4, carb: 20, fiber: 5, portion: 180 },
  { id: 'green-peas-canned', name: 'Горошек зелёный консервированный', kcal: 55, protein: 3.6, fat: 0.2, carb: 9.8, portion: 100 },
  { id: 'green-beans-boiled', name: 'Фасоль стручковая варёная', kcal: 35, protein: 2, fat: 0.2, carb: 5, portion: 150 },
  { id: 'soy-boiled', name: 'Соя варёная', kcal: 145, protein: 14, fat: 6.5, carb: 8, portion: 120 },
  { id: 'tofu', name: 'Тофу', kcal: 76, protein: 8, fat: 4.8, carb: 1.9, portion: 100 },
  { id: 'hummus', name: 'Хумус', kcal: 240, protein: 8, fat: 15, carb: 18, portion: 50 },

  // ─────────────────────────────────────────── овощи и грибы
  { id: 'cucumber', name: 'Огурец свежий', kcal: 15, protein: 0.8, fat: 0.1, carb: 2.8, portion: 100 },
  { id: 'cucumber-pickled', name: 'Огурцы солёные', kcal: 11, protein: 0.8, fat: 0.1, carb: 1.7, portion: 100 },
  { id: 'tomato', name: 'Помидор свежий', kcal: 20, protein: 1.1, fat: 0.2, carb: 3.7, portion: 100 },
  { id: 'tomato-cherry', name: 'Помидоры черри', kcal: 22, protein: 1, fat: 0.2, carb: 4, portion: 100 },
  { id: 'cabbage-white', name: 'Капуста белокочанная свежая', kcal: 28, protein: 1.8, fat: 0.1, carb: 4.7, portion: 100 },
  { id: 'cabbage-stewed', name: 'Капуста тушёная', kcal: 50, protein: 1.6, fat: 2.5, carb: 6, portion: 200 },
  { id: 'cabbage-sauerkraut', name: 'Капуста квашеная', kcal: 19, protein: 1.8, fat: 0.1, carb: 3, portion: 100 },
  { id: 'broccoli-boiled', name: 'Брокколи варёная', kcal: 35, protein: 2.8, fat: 0.4, carb: 5, portion: 150 },
  { id: 'cauliflower-boiled', name: 'Цветная капуста варёная', kcal: 29, protein: 1.8, fat: 0.3, carb: 4.2, portion: 150 },
  { id: 'carrot-raw', name: 'Морковь свежая', kcal: 35, protein: 1.3, fat: 0.1, carb: 6.9, portion: 100 },
  { id: 'carrot-boiled', name: 'Морковь варёная', kcal: 35, protein: 0.8, fat: 0.2, carb: 7, portion: 100 },
  { id: 'beetroot-boiled', name: 'Свёкла варёная', kcal: 49, protein: 1.8, fat: 0.1, carb: 10.8, portion: 100 },
  { id: 'onion', name: 'Лук репчатый', kcal: 41, protein: 1.4, fat: 0.2, carb: 8.2, portion: 50 },
  { id: 'onion-green', name: 'Лук зелёный', kcal: 20, protein: 1.3, fat: 0.1, carb: 3.2, portion: 30 },
  { id: 'garlic', name: 'Чеснок', kcal: 143, protein: 6.5, fat: 0.5, carb: 29, portion: 5 },
  { id: 'bell-pepper', name: 'Перец болгарский', kcal: 27, protein: 1.3, fat: 0.1, carb: 5.3, portion: 100 },
  { id: 'zucchini-stewed', name: 'Кабачок тушёный', kcal: 40, protein: 0.9, fat: 2.5, carb: 4, portion: 200 },
  { id: 'eggplant-baked', name: 'Баклажан запечённый', kcal: 55, protein: 1.2, fat: 3, carb: 5, portion: 150 },
  { id: 'pumpkin-baked', name: 'Тыква запечённая', kcal: 45, protein: 1.2, fat: 0.4, carb: 9, portion: 150 },
  { id: 'radish', name: 'Редис', kcal: 20, protein: 1.2, fat: 0.1, carb: 3.4, portion: 100 },
  { id: 'lettuce', name: 'Салат листовой', kcal: 15, protein: 1.4, fat: 0.2, carb: 2, portion: 50 },
  { id: 'spinach', name: 'Шпинат свежий', kcal: 23, protein: 2.9, fat: 0.4, carb: 2, portion: 50 },
  { id: 'arugula', name: 'Руккола', kcal: 25, protein: 2.6, fat: 0.7, carb: 2, portion: 30 },
  { id: 'dill', name: 'Укроп', kcal: 40, protein: 2.5, fat: 0.5, carb: 6, portion: 10 },
  { id: 'parsley', name: 'Петрушка', kcal: 47, protein: 3.7, fat: 0.4, carb: 8, portion: 10 },
  { id: 'champignon-raw', name: 'Шампиньоны свежие', kcal: 27, protein: 4.3, fat: 1, carb: 0.6, portion: 150 },
  { id: 'champignon-fried', name: 'Шампиньоны жареные', kcal: 60, protein: 3.5, fat: 4, carb: 2, portion: 150 },
  { id: 'oyster-mushroom-fried', name: 'Вешенки жареные', kcal: 65, protein: 2.8, fat: 5, carb: 2, portion: 150 },
  { id: 'corn-canned', name: 'Кукуруза консервированная', kcal: 58, protein: 2.2, fat: 0.6, carb: 11, portion: 80 },
  { id: 'olives-green', name: 'Оливки', kcal: 145, protein: 0.8, fat: 15, carb: 1.3, portion: 30 },
  { id: 'olives-black', name: 'Маслины', kcal: 165, protein: 0.9, fat: 17, carb: 1, portion: 30 },
  { id: 'avocado', name: 'Авокадо', kcal: 160, protein: 2, fat: 15, carb: 8.5, fiber: 6.7, portion: 100 },

  // ─────────────────────────────────────────── салаты и супы
  { id: 'salad-vegetable-oil', name: 'Салат овощной с маслом', kcal: 70, protein: 1.2, fat: 5, carb: 5, portion: 200 },
  { id: 'salad-vinegret', name: 'Винегрет', kcal: 90, protein: 1.4, fat: 5.5, carb: 8, portion: 200 },
  { id: 'salad-caesar-chicken', name: 'Салат «Цезарь» с курицей', kcal: 190, protein: 12, fat: 13, carb: 5, portion: 200 },
  { id: 'borsch-beef', name: 'Борщ с говядиной', kcal: 60, protein: 3.5, fat: 3, carb: 5, portion: 300 },
  { id: 'shchi', name: 'Щи из свежей капусты', kcal: 40, protein: 1.5, fat: 2, carb: 4, portion: 300 },
  { id: 'soup-chicken-noodle', name: 'Суп куриный с лапшой', kcal: 55, protein: 3, fat: 2, carb: 6, portion: 300 },
  { id: 'soup-pea', name: 'Суп гороховый', kcal: 65, protein: 3.5, fat: 2, carb: 9, portion: 300 },
  { id: 'ukha', name: 'Уха', kcal: 45, protein: 4, fat: 1.5, carb: 3.5, portion: 300 },
  { id: 'solyanka', name: 'Солянка мясная', kcal: 90, protein: 5, fat: 6, carb: 3, portion: 300 },
  { id: 'soup-mushroom-cream', name: 'Крем-суп грибной', kcal: 70, protein: 2, fat: 5, carb: 5, portion: 250 },
  { id: 'soup-vegetable', name: 'Суп овощной', kcal: 35, protein: 1.2, fat: 1.5, carb: 4.5, portion: 300 },
  { id: 'rassolnik', name: 'Рассольник', kcal: 55, protein: 2, fat: 2.5, carb: 6, portion: 300 },
  { id: 'okroshka-kefir', name: 'Окрошка на кефире', kcal: 60, protein: 3, fat: 2.5, carb: 6, portion: 300 },

  // ─────────────────────────────────────────── фрукты и ягоды
  { id: 'apple', name: 'Яблоко', kcal: 47, protein: 0.4, fat: 0.4, carb: 9.8, portion: 180, units: [{ name: '1 шт', grams: 180 }] },
  { id: 'pear', name: 'Груша', kcal: 42, protein: 0.4, fat: 0.3, carb: 10.3, portion: 170, units: [{ name: '1 шт', grams: 170 }] },
  { id: 'banana', name: 'Банан', kcal: 95, protein: 1.5, fat: 0.2, carb: 21, portion: 120, units: [{ name: '1 шт', grams: 120 }] },
  { id: 'orange', name: 'Апельсин', kcal: 43, protein: 0.9, fat: 0.2, carb: 8.1, portion: 200, units: [{ name: '1 шт', grams: 200 }] },
  { id: 'tangerine', name: 'Мандарин', kcal: 38, protein: 0.8, fat: 0.2, carb: 7.5, portion: 80, units: [{ name: '1 шт', grams: 80 }] },
  { id: 'grapefruit', name: 'Грейпфрут', kcal: 35, protein: 0.7, fat: 0.2, carb: 6.5, portion: 200 },
  { id: 'lemon', name: 'Лимон', kcal: 16, protein: 0.9, fat: 0.1, carb: 3, portion: 20 },
  { id: 'kiwi', name: 'Киви', kcal: 47, protein: 1, fat: 0.6, carb: 10, portion: 80, units: [{ name: '1 шт', grams: 80 }] },
  { id: 'grapes', name: 'Виноград', kcal: 65, protein: 0.6, fat: 0.2, carb: 15, portion: 100 },
  { id: 'peach', name: 'Персик', kcal: 45, protein: 0.9, fat: 0.1, carb: 9.5, portion: 150 },
  { id: 'apricot', name: 'Абрикос', kcal: 44, protein: 0.9, fat: 0.1, carb: 9, portion: 40 },
  { id: 'plum', name: 'Слива', kcal: 42, protein: 0.8, fat: 0.3, carb: 9.6, portion: 40 },
  { id: 'pineapple', name: 'Ананас', kcal: 49, protein: 0.4, fat: 0.2, carb: 11.5, portion: 100 },
  { id: 'mango', name: 'Манго', kcal: 60, protein: 0.8, fat: 0.4, carb: 15, portion: 150 },
  { id: 'persimmon', name: 'Хурма', kcal: 67, protein: 0.5, fat: 0.4, carb: 15.9, portion: 150 },
  { id: 'pomegranate', name: 'Гранат', kcal: 72, protein: 0.9, fat: 0.6, carb: 14.5, portion: 150 },
  { id: 'watermelon', name: 'Арбуз', kcal: 27, protein: 0.6, fat: 0.1, carb: 5.8, portion: 300 },
  { id: 'melon', name: 'Дыня', kcal: 35, protein: 0.6, fat: 0.3, carb: 7.4, portion: 200 },
  { id: 'strawberry', name: 'Клубника', kcal: 33, protein: 0.8, fat: 0.4, carb: 7, portion: 150 },
  { id: 'raspberry', name: 'Малина', kcal: 46, protein: 0.8, fat: 0.5, carb: 8.3, fiber: 6.5, portion: 100 },
  { id: 'blueberry-forest', name: 'Черника', kcal: 44, protein: 1.1, fat: 0.4, carb: 8, fiber: 3, portion: 100 },
  { id: 'blueberry-garden', name: 'Голубика', kcal: 39, protein: 1, fat: 0.5, carb: 6.6, fiber: 2.5, portion: 100 },
  { id: 'blackcurrant', name: 'Смородина чёрная', kcal: 44, protein: 1, fat: 0.4, carb: 7.3, fiber: 4.8, portion: 100 },
  { id: 'cherry-sour', name: 'Вишня', kcal: 52, protein: 0.8, fat: 0.2, carb: 10.6, portion: 100 },
  { id: 'cherry-sweet', name: 'Черешня', kcal: 63, protein: 1.1, fat: 0.4, carb: 12, portion: 100 },
  { id: 'cranberry', name: 'Клюква', kcal: 26, protein: 0.5, fat: 0.2, carb: 4, fiber: 3.3, portion: 50 },
  { id: 'raisins', name: 'Изюм', kcal: 264, protein: 2.9, fat: 0.6, carb: 62, portion: 30, isSweet: true },
  { id: 'dried-apricots', name: 'Курага', kcal: 232, protein: 5.2, fat: 0.3, carb: 51, portion: 30, isSweet: true },
  { id: 'prunes', name: 'Чернослив', kcal: 231, protein: 2.3, fat: 0.7, carb: 57.5, portion: 30, isSweet: true },
  { id: 'dates', name: 'Финики', kcal: 292, protein: 2.5, fat: 0.5, carb: 69, portion: 30, isSweet: true },

  // ─────────────────────────────────────────── орехи, семена, масла
  { id: 'walnut', name: 'Грецкий орех', kcal: 654, protein: 15, fat: 65, carb: 7, portion: 30 },
  { id: 'almond', name: 'Миндаль', kcal: 579, protein: 21, fat: 50, carb: 9, portion: 30 },
  { id: 'cashew', name: 'Кешью', kcal: 553, protein: 18, fat: 44, carb: 26, portion: 30 },
  { id: 'hazelnut', name: 'Фундук', kcal: 628, protein: 15, fat: 61, carb: 7, portion: 30 },
  { id: 'pistachio', name: 'Фисташки', kcal: 560, protein: 20, fat: 45, carb: 28, portion: 30 },
  { id: 'peanut-roasted', name: 'Арахис жареный', kcal: 585, protein: 26, fat: 49, carb: 10, portion: 30 },
  { id: 'pine-nut', name: 'Кедровый орех', kcal: 673, protein: 14, fat: 68, carb: 13, portion: 20 },
  { id: 'sunflower-seeds', name: 'Семечки подсолнечника', kcal: 578, protein: 21, fat: 53, carb: 10, portion: 30 },
  { id: 'pumpkin-seeds', name: 'Семена тыквы', kcal: 559, protein: 30, fat: 49, carb: 11, portion: 30 },
  { id: 'chia-seeds', name: 'Семена чиа', kcal: 486, protein: 17, fat: 31, carb: 42, fiber: 34, portion: 20 },
  { id: 'flax-seeds', name: 'Семена льна', kcal: 534, protein: 18, fat: 42, carb: 29, fiber: 27, portion: 20 },
  { id: 'sesame', name: 'Кунжут', kcal: 573, protein: 18, fat: 50, carb: 23, portion: 10 },
  { id: 'peanut-butter', name: 'Арахисовая паста', kcal: 588, protein: 25, fat: 50, carb: 20, portion: 20 },
  { id: 'coconut-flakes', name: 'Кокосовая стружка', kcal: 592, protein: 6.9, fat: 62, carb: 23, fiber: 16, portion: 15 },
  { id: 'oil-sunflower', name: 'Масло подсолнечное', kcal: 899, protein: 0, fat: 99.9, carb: 0, portion: 10 },
  { id: 'oil-olive', name: 'Масло оливковое', kcal: 898, protein: 0, fat: 99.8, carb: 0, portion: 10 },
  { id: 'oil-flax', name: 'Масло льняное', kcal: 898, protein: 0, fat: 99.8, carb: 0, portion: 10 },
  { id: 'oil-coconut', name: 'Масло кокосовое', kcal: 899, protein: 0, fat: 99.9, carb: 0, portion: 10 },
  { id: 'mayonnaise', name: 'Майонез', kcal: 620, protein: 1, fat: 67, carb: 2.6, portion: 20 },
  { id: 'mayonnaise-light', name: 'Майонез лёгкий', kcal: 350, protein: 0.7, fat: 35, carb: 5, portion: 20 },

  // ─────────────────────────────────────────── хлеб и выпечка
  { id: 'bread-white', name: 'Хлеб белый', kcal: 260, protein: 8, fat: 3, carb: 48, portion: 30, units: [{ name: '1 ломтик', grams: 30 }] },
  { id: 'bread-rye', name: 'Хлеб ржаной', kcal: 210, protein: 6.6, fat: 1.2, carb: 41, portion: 30, units: [{ name: '1 ломтик', grams: 30 }] },
  { id: 'bread-borodinsky', name: 'Хлеб бородинский', kcal: 208, protein: 6.8, fat: 1.3, carb: 40, portion: 30, units: [{ name: '1 ломтик', grams: 30 }] },
  { id: 'bread-wholegrain', name: 'Хлеб цельнозерновой', kcal: 230, protein: 9, fat: 3.5, carb: 38, fiber: 6, portion: 30, units: [{ name: '1 ломтик', grams: 30 }] },
  { id: 'baton', name: 'Батон нарезной', kcal: 264, protein: 7.5, fat: 2.9, carb: 51, portion: 30, units: [{ name: '1 ломтик', grams: 30 }] },
  { id: 'lavash', name: 'Лаваш тонкий', kcal: 275, protein: 9, fat: 1, carb: 56, portion: 60 },
  { id: 'baguette', name: 'Багет', kcal: 262, protein: 8, fat: 1.5, carb: 52, portion: 50 },
  { id: 'pita-wholegrain', name: 'Пита цельнозерновая', kcal: 260, protein: 9, fat: 2, carb: 50, portion: 60 },
  { id: 'crispbread-rye', name: 'Хлебцы ржаные', kcal: 310, protein: 11, fat: 2.5, carb: 57, fiber: 15, portion: 20, units: [{ name: '1 хлебец', grams: 10 }] },
  { id: 'breadcrumbs', name: 'Сухари панировочные', kcal: 350, protein: 11, fat: 2, carb: 70, portion: 20 },
  { id: 'bun-sweet', name: 'Булочка сдобная', kcal: 300, protein: 7.5, fat: 6, carb: 52, portion: 70, isSweet: true },
  { id: 'croissant', name: 'Круассан', kcal: 406, protein: 8, fat: 21, carb: 45, portion: 60, isSweet: true },
  { id: 'croissant-chocolate', name: 'Круассан с шоколадом', kcal: 450, protein: 7, fat: 24, carb: 50, portion: 70, isSweet: true },
  { id: 'pirozhok-potato', name: 'Пирожок с картошкой жареный', kcal: 280, protein: 5, fat: 12, carb: 38, portion: 90 },
  { id: 'bliny', name: 'Блины', kcal: 230, protein: 6, fat: 8, carb: 33, portion: 100 },
  { id: 'oladyi', name: 'Оладьи', kcal: 280, protein: 6.5, fat: 12, carb: 37, portion: 100 },
  { id: 'syrniki', name: 'Сырники', kcal: 220, protein: 17, fat: 8, carb: 20, portion: 130 },
  { id: 'pizza-margherita', name: 'Пицца «Маргарита»', kcal: 250, protein: 10, fat: 9, carb: 33, portion: 200 },
  { id: 'shaurma-chicken', name: 'Шаурма с курицей', kcal: 210, protein: 11, fat: 9, carb: 22, portion: 300 },
  { id: 'burger', name: 'Бургер', kcal: 280, protein: 13, fat: 14, carb: 26, portion: 200 },
  { id: 'hot-dog', name: 'Хот-дог', kcal: 260, protein: 10, fat: 14, carb: 24, portion: 150 },

  // ─────────────────────────────────────────── сладкое
  { id: 'sugar', name: 'Сахар', kcal: 399, protein: 0, fat: 0, carb: 99.8, portion: 5, isSweet: true },
  { id: 'honey', name: 'Мёд', kcal: 329, protein: 0.8, fat: 0, carb: 81, portion: 20, isSweet: true },
  { id: 'chocolate-milk', name: 'Шоколад молочный', kcal: 550, protein: 6.9, fat: 35, carb: 54, portion: 25, isSweet: true },
  { id: 'chocolate-dark', name: 'Шоколад тёмный 70%', kcal: 540, protein: 8, fat: 40, carb: 34, portion: 25, isSweet: true },
  { id: 'chocolate-white', name: 'Шоколад белый', kcal: 555, protein: 6, fat: 32, carb: 59, portion: 25, isSweet: true },
  { id: 'candy-chocolate', name: 'Конфеты шоколадные', kcal: 520, protein: 4, fat: 28, carb: 62, portion: 20, isSweet: true },
  { id: 'caramel', name: 'Карамель', kcal: 375, protein: 0, fat: 0.1, carb: 95, portion: 15, isSweet: true },
  { id: 'marmalade', name: 'Мармелад', kcal: 320, protein: 0.4, fat: 0.1, carb: 78, portion: 30, isSweet: true },
  { id: 'zefir', name: 'Зефир', kcal: 326, protein: 0.8, fat: 0.1, carb: 79, portion: 30, isSweet: true },
  { id: 'pastila', name: 'Пастила', kcal: 324, protein: 0.5, fat: 0, carb: 80, portion: 30, isSweet: true },
  { id: 'halva', name: 'Халва подсолнечная', kcal: 520, protein: 11, fat: 30, carb: 50, portion: 30, isSweet: true },
  { id: 'cookie-oatmeal', name: 'Печенье овсяное', kcal: 440, protein: 6, fat: 16, carb: 68, portion: 25, isSweet: true },
  { id: 'cookie-shortbread', name: 'Печенье песочное', kcal: 460, protein: 6, fat: 22, carb: 60, portion: 25, isSweet: true },
  { id: 'cookie-plain', name: 'Печенье сахарное', kcal: 450, protein: 7, fat: 15, carb: 70, portion: 25, isSweet: true },
  { id: 'waffles', name: 'Вафли', kcal: 500, protein: 4, fat: 28, carb: 60, portion: 25, isSweet: true },
  { id: 'pryaniki', name: 'Пряники', kcal: 350, protein: 5, fat: 3, carb: 75, portion: 40, isSweet: true },
  { id: 'cake-sponge', name: 'Торт бисквитный с кремом', kcal: 400, protein: 5, fat: 20, carb: 50, portion: 100, isSweet: true },
  { id: 'cheesecake', name: 'Чизкейк', kcal: 320, protein: 6, fat: 20, carb: 28, portion: 100, isSweet: true },
  { id: 'eclair', name: 'Эклер', kcal: 380, protein: 6, fat: 22, carb: 40, portion: 80, isSweet: true },
  { id: 'roll-sponge', name: 'Рулет бисквитный', kcal: 370, protein: 5, fat: 12, carb: 60, portion: 60, isSweet: true },
  { id: 'donut', name: 'Пончик', kcal: 420, protein: 6, fat: 22, carb: 50, portion: 70, isSweet: true },
  { id: 'keks', name: 'Кекс', kcal: 380, protein: 6, fat: 15, carb: 56, portion: 70, isSweet: true },
  { id: 'jam-strawberry', name: 'Варенье клубничное', kcal: 270, protein: 0.4, fat: 0.1, carb: 67, portion: 30, isSweet: true },
  { id: 'jam-apricot', name: 'Джем абрикосовый', kcal: 265, protein: 0.4, fat: 0.1, carb: 66, portion: 30, isSweet: true },
  { id: 'chocolate-spread', name: 'Шоколадная паста', kcal: 540, protein: 6, fat: 31, carb: 58, portion: 20, isSweet: true },
  { id: 'chocolate-bar-snack', name: 'Батончик шоколадный с орехами', kcal: 490, protein: 8, fat: 24, carb: 60, portion: 50, isSweet: true },
  { id: 'protein-bar', name: 'Протеиновый батончик', kcal: 350, protein: 30, fat: 10, carb: 35, portion: 50, isSweet: true },

  // ─────────────────────────────────────────── напитки
  { id: 'water', name: 'Вода', kcal: 0, protein: 0, fat: 0, carb: 0, portion: 250, units: [{ name: '1 стакан', grams: 250 }] },
  { id: 'tea-plain', name: 'Чай без сахара', kcal: 0, protein: 0, fat: 0, carb: 0, portion: 250 },
  { id: 'coffee-black', name: 'Кофе чёрный без сахара', kcal: 2, protein: 0.2, fat: 0, carb: 0.3, portion: 200 },
  { id: 'coffee-milk', name: 'Кофе с молоком', kcal: 30, protein: 1.5, fat: 1.5, carb: 2.8, portion: 200 },
  { id: 'cappuccino', name: 'Капучино', kcal: 45, protein: 2.4, fat: 2, carb: 4, portion: 250 },
  { id: 'latte', name: 'Латте', kcal: 55, protein: 3, fat: 2.5, carb: 5, portion: 300 },
  { id: 'cocoa-milk', name: 'Какао на молоке', kcal: 80, protein: 3.2, fat: 3, carb: 10, portion: 250, isSweet: true },
  { id: 'juice-orange', name: 'Сок апельсиновый', kcal: 45, protein: 0.7, fat: 0.1, carb: 10, portion: 250 },
  { id: 'juice-apple', name: 'Сок яблочный', kcal: 46, protein: 0.5, fat: 0.1, carb: 11, portion: 250 },
  { id: 'juice-tomato', name: 'Сок томатный', kcal: 21, protein: 1, fat: 0.2, carb: 4, portion: 250 },
  { id: 'mors-berry', name: 'Морс ягодный', kcal: 40, protein: 0.1, fat: 0, carb: 10, portion: 250 },
  { id: 'kompot-dried-fruit', name: 'Компот из сухофруктов', kcal: 60, protein: 0.4, fat: 0, carb: 15, portion: 250, isSweet: true },
  { id: 'cola', name: 'Кола', kcal: 42, protein: 0, fat: 0, carb: 10.6, portion: 330, isSweet: true },
  { id: 'cola-zero', name: 'Кола без сахара', kcal: 0.3, protein: 0, fat: 0, carb: 0, portion: 330 },
  { id: 'energy-drink', name: 'Энергетик', kcal: 45, protein: 0, fat: 0, carb: 11, portion: 250, isSweet: true },
  { id: 'beer-light', name: 'Пиво светлое 4.5%', kcal: 43, protein: 0.5, fat: 0, carb: 3.6, alcohol: 3.6, portion: 500 },
  { id: 'wine-dry-red', name: 'Вино сухое красное', kcal: 68, protein: 0.2, fat: 0, carb: 0.3, alcohol: 9.5, portion: 150 },
  { id: 'champagne-brut', name: 'Шампанское брют', kcal: 70, protein: 0.2, fat: 0, carb: 1.5, alcohol: 9, portion: 150 },
  { id: 'vodka', name: 'Водка', kcal: 231, protein: 0, fat: 0, carb: 0.1, alcohol: 31.6, portion: 50 },
  { id: 'whisky', name: 'Виски', kcal: 250, protein: 0, fat: 0, carb: 0, alcohol: 31.6, portion: 50 },

  // ─────────────────────────────────────────── соусы, приправы, спортпит
  { id: 'ketchup', name: 'Кетчуп', kcal: 100, protein: 1.5, fat: 0.3, carb: 23, portion: 20 },
  { id: 'soy-sauce', name: 'Соевый соус', kcal: 55, protein: 6, fat: 0, carb: 6, portion: 15 },
  { id: 'mustard', name: 'Горчица', kcal: 145, protein: 9, fat: 8, carb: 6, portion: 10 },
  { id: 'adjika', name: 'Аджика', kcal: 60, protein: 1, fat: 3, carb: 7, portion: 15 },
  { id: 'tomato-paste', name: 'Томатная паста', kcal: 100, protein: 4.8, fat: 0.5, carb: 19, portion: 30 },
  { id: 'sour-cream-sauce', name: 'Сметанный соус', kcal: 180, protein: 2.5, fat: 17, carb: 4, portion: 30 },
  { id: 'pesto', name: 'Соус песто', kcal: 450, protein: 5, fat: 45, carb: 6, portion: 20 },
  { id: 'balsamic-vinegar', name: 'Уксус бальзамический', kcal: 88, protein: 0.5, fat: 0, carb: 19, portion: 10 },
  { id: 'salt', name: 'Соль', kcal: 0, protein: 0, fat: 0, carb: 0, portion: 2 },
  { id: 'whey-protein-powder', name: 'Протеин сывороточный (порошок)', kcal: 380, protein: 75, fat: 6, carb: 8, portion: 30 },
  { id: 'casein-powder', name: 'Казеин (порошок)', kcal: 370, protein: 72, fat: 3, carb: 9, portion: 30 },
];
