export { roundTo } from './round.js';
export { loginSchema, type LoginInput, type SessionInfo } from './auth.js';
export {
  ACTIVITY_FACTORS,
  DEFAULT_DEFICIT,
  DEFAULT_FAT_PER_KG,
  DEFAULT_PROTEIN_PER_KG,
  DEFAULT_SWEETS_SHARE,
  MIN_TARGET_KCAL,
  calcAge,
  calcBmr,
  calcCarbTarget,
  calcMacroTargets,
  calcSweetsBudget,
  calcTargetKcal,
  calcTdee,
  computeTargets,
  effectiveTargets,
  type ActivityLevel,
  type Deficit,
  type DeficitMode,
  type EffectiveTargets,
  type MissingField,
  type Sex,
  type Targets,
  type TargetOverrides,
  type TargetsInput,
} from './nutrition.js';
export {
  profileUpdateSchema,
  type Profile,
  type ProfileResponse,
  type ProfileUpdate,
} from './profile.js';
export {
  DEFAULT_TIMEZONE,
  dateColumnToIso,
  isIsoDate,
  isoToDateColumn,
  shiftIsoDate,
  toIsoDate,
  toTimeOfDay,
  todayIso,
  type IsoDate,
} from './date.js';
export { mealTypeByTime, parseTimeOfDay, type MealType } from './mealType.js';
export { queryVariants, switchLayout } from './layout.js';
export {
  ZERO_NUTRIENTS,
  amountToGrams,
  remaining,
  scaleNutrients,
  sumNutrients,
  sumSweetKcal,
  type AmountUnit,
  type Nutrients,
  type Per100,
} from './portion.js';
export {
  CHART_PERIODS,
  EMA_ALPHA,
  MIN_RATE_MEASUREMENTS,
  RATE_CORRIDOR,
  RATE_WINDOW_DAYS,
  TREND_WINDOW_DAYS,
  calcCurrentTrend,
  calcForecast,
  calcRate,
  calcTrendSeries,
  daysBetween,
  filterFromDate,
  isRateInCorridor,
  ratePercentOfBody,
  weightUpsertSchema,
  type ChartPeriod,
  type Forecast,
  type Measurement,
  type TrendPoint,
  type WeightSeriesResponse,
  type WeightStats,
  type WeightUpsert,
} from './weight.js';
export {
  diaryCreateSchema,
  diaryUpdateSchema,
  foodCreateSchema,
  foodSearchSchema,
  foodUpdateSchema,
  waterUpdateSchema,
  type DiaryCreate,
  type DiaryDay,
  type DiaryEntryInfo,
  type DiaryUpdate,
  type FoodCreate,
  type FoodInfo,
  type FoodUnitInfo,
  type FoodUpdate,
  type RecentFood,
  type RecentResponse,
  type WaterUpdate,
} from './diary.js';
